version: '3.8'

services:
  api:
    image: username/demo:api-latest
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data

  frontend:
    image: username/demo:frontend-latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  console:
    image: username/demo:console-latest
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - api


  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend/public:/var/www/certbot

  certbot-renew:
    image: certbot/certbot
    entrypoint: sh -c "while :; do certbot renew; sleep 12h; done"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  sqlite_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
