name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:api-latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:api-latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:frontend-latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:frontend-latest

      - name: Build & Push Console
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:console-latest ./console
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/remote-shell:console-latest
